version: "3.7"

services:
  database_mycircle:
    image: postgres
    container_name: database_mycircle
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mycircle
      - POSTGRES_DB=mycircle
    volumes:
      - pgdata:/data/postgres
      - ./src/database:/docker-entrypoint-initdb.d

volumes:
  pgdata:
    driver: local

